### PR TITLE
Why can't we be friends?

### PR DESCRIPTION
**Pull request by NathanDeMaria**
The user stuff I added friends to is from our backend stuff (User.cs), which != the user stuff made by SimpleMembership (UserProfile), so this won't work :frowning: for friends because the User table is empty

### CODE REVIEW

**Comment by Rumel** [comment]
I think we need to enable migrations. I got that to work with simple membership yesterday but I didn't get the actual database to work. If we can get the app to use one db with migrations I think this will be fixed. [Hopefully Helpful Link](http://ilmatte.wordpress.com/2012/12/05/entity-framework-5-code-first-enabling-migrations-in-a-real-project/)

**Comment by NathanDeMaria** [comment]
Do we need to worry about moving the AccountModels classes to the backend with the rest of our database? The classes in AccountModels for users actually do what the User model we currently have in the backend was made for

**Comment by Rumel** [comment]
Ok so I just committed some changes and I need people to test it. Just to make everything simple you should delete anything in your Radabite/App_Data folder and then you should the code. Both events and simple membership were working for me. I verified simple membership by just running the app and then to verify events I just went to `/api/v1/events` this will return `[ ]` which is cool.

**Comment by NathanDeMaria** [comment]
Everything here is ready, except for merge conflicts with csproj. I switched back to dummy friends because the database part is dependent on moving the AccountModel to our backend

**Pull request merged**
